version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

workflows:
  compose_push:
    jobs:
      - build
      - approve_to_push:
          type: approval
          requires:
            - build
      - push:
          filters:
            branches:
              only:
                - main
                - circleci
          requires:
            - approve_to_push

jobs:
  build:
    working_directory: ~/cal-event
    docker:
      - image: composer
    steps:
      - checkout
      - run:
          name: Compose
          command: composer install
  push:
    working_directory: ~/cal-event
    docker:
      - image: composer
    executor: gcp-cli/default
    steps:
      - checkout
      - run:
          name: Compose
          command: composer install
      - gcp-cli/install
      - run: ls ~/cal-event