version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.1.0

workflows:
  compose_push:
    jobs:
      - build
      - approve_to_push:
          type: approval
          requires:
            - build
      - push:
          context:
            - Default
          filters:
            branches:
              only:
                - main
          requires:
            - approve_to_push

jobs:
  build:
    working_directory: ~/cal-event
    docker:
      - image: composer
    steps:
      - checkout
      - run:
          name: Compose
          command: composer install
  push:
    working_directory: ~/cal-event
    docker:
      - image: composer
    executor: gcp-cli/default
    steps:
      - checkout
      - run:
          name: Compose
          command: composer install
      - gcp-cli/install
      - gcp-cli/initialize
      - run: ls ~/cal-event
      - run:
          name: Push to labs
          command: |
            gcloud compute scp --recurse ~/cal-event add-lamp-vm:/var/www/labs/html/cal-event --ssh-key-file=${HOME}/gcloud-service-key.json